### ISSUE TITLE
Error 404 when trying to install userscripts

### ISSUE THREAD

**Issue by Hunter16g** [karamanolev/WhatManager2#101]
It seems I can't install any of the userscripts apart from Overdrive search, I get a 404 error for http://localhost/userscript/localhost/static/js/jquery.noty.packaged.min.js

**Comment by faircopy** [comment]
This looks like you've set `USERSCRIPT_WM_ROOT = 'http://localhost/userscript/localhost'` in `settings.py`, resulting in the 10th line of the generated userscript file being:
`// @require http://localhost/userscript/localhost/static/js/jquery.noty.packaged.min.js`

I'm assuming you're hosting WhatManager under http://localhost. If this is the case, the above line should be:
`// @require http://localhost/static/js/jquery.noty.packaged.min.js`

To fix:
- Stop webserver (Apache)
- Modify `settings.py`: `USERSCRIPT_WM_ROOT = 'http://localhost'`
- Start webserver
- Install userscript

**Comment by Hunter16g** [comment]
The line was indeed incorrect, I didn't put the http:// (just 'localhost'). Thank you !
