### ISSUE TITLE
Transcoder stuck on "pending transcoding"

### ISSUE THREAD

**Issue by montchr** [karamanolev/WhatManager2#107]
I've added a torrent to transcode at mysite.com/transcode. It will download the files, and after that displays the message "download complete. transcoding should start within 1 minute." But after that message goes away, it's replaced by a "pending transcoding" message which never goes away, and the transcode is never completed.

**Comment by 2600box** [comment]
are you running the celery script in the background? check the wiki

**Comment by montchr** [comment]
Thanks, that definitely helped – I ran `python manage.py celery worker --loglevel=info --concurrency=1` as suggested, which started transcoding. But how do I run this in the background without having to have a terminal window at all times? I've set up the cron job but that doesn't seem to do a thing.

**Comment by montchr** [comment]
If I run `curl http://host.com/transcode/update` in my terminal there's no response, so I'm not sure why running it with cron would be any different.

**Comment by montchr** [comment]
Nevermind – I looked more into using `screen` and that seems to be working. 😄 Thanks for the push in the right direction.
