### ISSUE TITLE
Can't transcode single-track albums

### ISSUE THREAD

**Issue by montchr** [karamanolev/WhatManager2#108]
If an album legitimately only has one track, the transcoder won't transcode it, throwing this error:

```
failed - Exception(This is a single audio file torrent that is not a single or a remix in Redacted. Will not transcode.)
```

Is this restriction helpful at all, considering that a transcode will always be of a release that's already uploaded?

**Comment by karamanolev** [comment]
Yes. After one or two times when you get warned because there was a release uploaded, but it was wrong you'll appreciate it. However, WM2 is very developer-friendly :D feel free to comment it out and live happily ever after.
