### ISSUE TITLE
Transcode upload fails because of missing edition information

### ISSUE THREAD

**Issue by OdinGitDat** [karamanolev/WhatManager2#123]
Following error is thrown when the FLAC being transcoded does not have edition information added.
`Exception(Error uploading data to Redacted. Errors: Year of remaster/re-issue must be entered.)`
Easily fixed by adding that information to the original torrent, but maybe something that can be integrated into wm.

**Comment by karamanolev** [comment]
@OdinGitDat Wouldn't this essentially be editing torrent metadata from within WM? I'm skeptical about this, you can probably tell why.

**Comment by OdinGitDat** [comment]
Well since redacted stopped allowing 'original release' uploads there are a lot of existing torrents left with no edition information. When transcoding one of these files it would be sensible to set 'edition year' to equal 'Initial year' on the upload page. That's my opinion though.
