### ISSUE TITLE
Can't edit transmission settings.json

### ISSUE THREAD

**Issue by LennyPenny** [karamanolev/WhatManager2#83]
When I edit the settings.json in my TRANSMISSION_FILES_ROOT and restart the daemon the settings file just gets overwritten by the default file. 
Is there any way I can maybe just edit the default settings.json that gets recopied there?

**Comment by MADindustries** [comment]
You have to stop the daemon before editing. Transmission overwrites the settings file when it shuts down.

**Comment by LennyPenny** [comment]
![https://vgy.me/ivgNa0.png](https://vgy.me/ivgNa0.png)

Sadly I can't confirm this behavior

**Comment by LennyPenny** [comment]
Ah nevermind it just automatically seems to reorder settings lines as well, thanks
