### ISSUE TITLE
Profile stats not updating

### ISSUE THREAD

**Issue by LennyPenny** [karamanolev/WhatManager2#88]
Somehow my profile stats stopped updating? 
![https://vgy.me/mAxyNI.png](https://vgy.me/mAxyNI.png)

**Comment by casedefault** [comment]
I think this might happen if your login session to RED expires?

Have you tried clearing the login cache? Instructions here: https://github.com/karamanolev/WhatManager2/wiki/Troubleshooting#failed---exception-error-uploading-data-to-whatcd-errors-no-further-info

**Comment by LennyPenny** [comment]
Didn't help :/

**Comment by LennyPenny** [comment]
I have also run
`./migrate clear_what_login_cache`

With to no success

**Comment by LennyPenny** [comment]
Seems to have fixed itself after I changed a lot of stuffs
