### ISSUE TITLE
Error retrieving new torrent

### ISSUE THREAD

**Issue by LennyPenny** [karamanolev/WhatManager2#99]
I'm guessing uploading the torrent failed for some reason. 
Any idea how I could debug this further? 

![https://vgy.me/AWQXJ1.png](https://vgy.me/AWQXJ1.png)

**Comment by LennyPenny** [comment]
Okay the error html says invalid authorization key

**Comment by LennyPenny** [comment]
running ./manage clear_what_login_cache also didn't seem to help

**Comment by montchr** [comment]
What fixed this issue for you? I'm having the same problem.

**Comment by LennyPenny** [comment]
I guess I just encountered other errors as specified in the newer issues :/ sorry to not be of help

**Comment by montchr** [comment]
@LennyPenny No worries, I quickly discovered it was connected to #102 – deleting the login cache worked as I noted in that issue too.
